-- CreateTable
CREATE TABLE `UserAvatar` (
    `UUID_UAV` VARCHAR(191) NOT NULL,
    `UUID_UA` VARCHAR(191) NOT NULL,
    `Url_UAV` VARCHAR(191) NOT NULL,
    `Filename_UAV` VARCHAR(191) NOT NULL,
    `isActive_UAV` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `UserAvatar_Url_UAV_key`(`Url_UAV`),
    PRIMARY KEY (`UUID_UAV`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `UserAvatar` ADD CONSTRAINT `UserAvatar_UUID_UA_fkey` FOREIGN KEY (`UUID_UA`) REFERENCES `UserAccount`(`UUID_UA`) ON DELETE RESTRICT ON UPDATE CASCADE;
