-- CreateTable
CREATE TABLE `GoldData` (
    `UUID_GD` VARCHAR(191) NOT NULL,
    `Sell_GD` VARCHAR(191) NOT NULL,
    `Buy_GD` VARCHAR(191) NOT NULL,
    `Type_GD` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`UUID_GD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
