-- CreateTable
CREATE TABLE `UserData` (
    `UUID_UD` VARCHAR(191) NOT NULL,
    `UUID_UA` VARCHAR(191) NOT NULL,
    `Gold_UD` DOUBLE NOT NULL DEFAULT 0,
    `Balance_UD` DOUBLE NOT NULL DEFAULT 0,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `UserData_UUID_UA_key`(`UUID_UA`),
    PRIMARY KEY (`UUID_UD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `UserData` ADD CONSTRAINT `UserData_UUID_UA_fkey` FOREIGN KEY (`UUID_UA`) REFERENCES `UserAccount`(`UUID_UA`) ON DELETE RESTRICT ON UPDATE CASCADE;
