-- CreateTable
CREATE TABLE `CardData` (
    `UUID_CD` VARCHAR(191) NOT NULL,
    `UUID_UA` VARCHAR(191) NOT NULL,
    `Seri_CD` VARCHAR(191) NOT NULL,
    `Weight_CD` DOUBLE NOT NULL,
    `Form_CD` VARCHAR(191) NOT NULL,
    `Fineness_CD` DOUBLE NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    PRIMARY KEY (`UUID_CD`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `CardData` ADD CONSTRAINT `CardData_UUID_UA_fkey` FOREIGN KEY (`UUID_UA`) REFERENCES `UserAccount`(`UUID_UA`) ON DELETE RESTRICT ON UPDATE CASCADE;
